export const DATA = [
  {
    description: 'Cheese',
    id: 1,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/margherita.90f9451fd66871fb6f9cf7d506053f18.1.jpg?width=550',
    name: 'Margherita',
    price: 3,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Spiced paneeer, Onion,Green Capsicum & Red Paprika in Tandoori Sauce',
    id: 2,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/tandoori-paneer.4ef45717e972cf45b43c010e3cde5a22.1.jpg?width=550',
    name: 'Tandoori Paneer',
    price: 7,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Black Olives,Green Capsicum, Mushroom, Onion,Red Paprika, Sweet Corn',
    id: 3,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veggie-supreme.bc8dd369182b636ff171077efa53c344.1.jpg?width=550',
    name: 'Veggie Supreme',
    price: 8,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description: 'Spiced Paneer, Herbed Onion&Green Capsicum, Red Paprika',
    id: 4,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/double-paneer-supreme.3cb382529b41d14d4a041b5cc5e64341.1.jpg?width=550',
    name: 'Double Paneer Supreme',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Veg Kebab,Onion,Green Capsicum,Tomato & Sweet Corn in Tandoori Sauce',
    id: 4,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veg-kebab-surprise.abab1dff179ab8cf95a59f30d6352297.1.jpg?width=550',
    name: 'Veggie Kebab Surprise',
    price: 4,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description: 'Herbed Chicken,Schezwan Chicken Meatball,Chicken Tikka',
    id: 5,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-supreme.6d53f104f071d304a47440f2fffa7378.1.jpg?width=550',
    name: 'Chicken Supreme',
    price: 7,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Chicken Tikka,Chicken Malai Tikka,Onion,Red Paprika',
    id: 6,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-tikka-supreme.830de5a911ca95a30e4ca98e529f1b3a.1.jpg?width=550',
    name: 'Chicken Tikka Supreme',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Schezwan Chicken Meatball Herbed Chicken,Chicken Sausage,Geen Capsicum, Onion,Red Paprika',
    id: 7,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/triple-chicken-feast.e4a546e7a8581a60952b99e3fe22987e.1.jpg?width=550',
    name: 'Triple Chicken Feast',
    price: 8,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Chicken Tikka, Onion, Tomato',
    id: 8,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-tikka.6d441a65371e941db36c2754586119a8.1.jpg?width=550',
    name: 'Chicken Tikka',
    price: 7,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Chicken Sausage',
    id: 9,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/double-chicken-sausage.f172dd6a365e90e655258b17555e74ad.1.jpg?width=550',
    name: 'Double Chicken Sausage',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Schezwan Chicken Meatball Onion',
    id: 10,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/spiced-chicken-meatballs.abd238e81080106d181567a9b52844ae.1.jpg?width=550',
    name: 'Spiced Chicken Meatballs',
    price: 4,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Extra Cheese on Cheese',
    id: 11,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/double-cheese.3c8885f8bc6f18facedc7626368f5105.1.jpg?width=550',
    name: 'Double Cheese',
    price: 3,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description: 'Herbed Chicken, Onion, Green Capsicum, Red Capsicum ',
    id: 12,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-pepper-crunch.624edb192601b73335e0100db5a6263a.1.jpg?width=550',
    name: 'Chicken Pepper Crunch',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Herbed Chicken, Onion, Green Capsicum, Red Capsicum ',
    id: 13,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/italian-chicken-feast.edad91a082e9a16d677722a071487a1c.1.jpg?width=550',
    name: 'Italian Chicken Feast',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Cheese ,Sweet Corn',
    id: 14,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/corn.f8baa08ad7f607f1de30f96bb9245b50.1.jpg?width=550',
    name: 'Corn & Cheese',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description: 'Cheese & Onion in Tandoori sause',
    id: 15,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/tandoori-onion.98e8cbd306a1166cedbbdbd2a97eade3.1.jpg?width=550',
    name: 'Tandoori Onion',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description: 'Cheese ,Chicken pepperoni',
    id: 16,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-pepperoni.6952ef03215b72477abff3574b4b881e.1.jpg?width=550',
    name: 'Chicken Pepperoni',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description: 'Cheese ,Chicken pepperoni',
    id: 17,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/chicken-n-corn-delight.61cc42effb2de18e6625796c964dd92d.1.jpg?width=550',
    name: 'Chicken N Corn Delight',
    price: 9,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Onion Herbed & Green Capsicum, Red Capsicum, Mushroom, Baby Corn',
    id: 18,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/farmers-pick.794695a631c14d4404057470020be703.1.jpg?width=550',
    name: 'Farmers Pick',
    price: 29,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with our Classic Pan sauce, sweet corn and cheesy dressing. An all-time favorite.',
    id: 19,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/classic-corn-pan-personal.7c80196383b32e2ad5715646c1b12df8.1.png?width=550',
    name: 'Classic Corn',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with our Classic Pan sauce, crunchy onion & capsicum and cheesy dressing.',
    id: 20,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/classic-onion-capsicum-pan-personal.dad788ecbd3fcc57366462827e31ee05.1.jpg?width=550',
    name: 'Classic Onion Capsicum',
    price: 4,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      "Pizza topped with our Chef's Special Italian sauce, crunchy onion, juicy tomatoes and cheesy dressing.",
    id: 21,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/italian-onion-tomato-pan-personal.cb37b0766ef3ba8844fa69b2d073c215.1.jpg?width=550',
    name: 'Italian Onion Tomato',
    price: 8,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with our signature tandoori sauce, juicy mushroom, sweet corn and cheesy dressing.',
    id: 22,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/tandoori-mushroom-&-sweet-corn-pan-personal.49a1287d1cece07781c106e552979fa2.1.jpg?width=550',
    name: 'Tandoori Mushroom & Sweet Corn',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with Spicy Schezwan sauce, sweet corn & crunchy capsicum and cheesy dressing.',
    id: 23,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/schezwan-corn-&-capsicum-pan-personal.23c83846270110a536b40ec74529e907.1.jpg?width=550',
    name: 'Schezwan Corn & Capsicum',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with cheesy dressing and mozzarella cheese for that extraaa cheesy flavor.',
    id: 24,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/only-cheesy-pan-personal.951dbe6ee07dafc48e04fe9a1bbe4ddb.1.jpg?width=550',
    name: 'Only Cheesy',
    price: 40,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      'Pizza topped with our Classic Pan sauce, flavorful chicken sausage and cheesy dressing.',
    id: 25,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/classic-sausage-pan-personal.fbbfbce57f62a8d8b366db5f66798704.1.jpg?width=550',
    name: 'Classic Sausage',
    price: 8,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Pizza topped with our Classic Pan sauce, flavorful paneer, crunchy onion & capsicum and cheesy dressing.',
    id: 26,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/classic-paneer-capsicum-&-onion-pan-personal.ae2c5f3e3e5881af1f31e65cb9526289.1.jpg?width=550',
    name: 'Classic Paneer Capsicum & Onion',
    price: 6,
    quantity: 1,
    sizeandcrust: [[]],
    veg: true,
  },
  {
    description:
      "Pizza topped with our Chef's Special Italian sauce, crunchy onion, chicken pepperoni and cheesy dressing.",
    id: 27,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/italian-pepperoni-&-onion-pan-personal.b6c0c99c9241f2fce14493773f625dd3.1.jpg?width=550',
    name: 'Italian Pepperoni & Onion',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Pizza topped with Spicy Schezwan sauce, crunchy capsicum, Schezwan meatballs and cheesy dressing making it spice lovers paradise.',
    id: 28,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/schezwan-meatball-&-capsicum-pan-personal.e27dd4520db7e81fbebeec8428a925bf.1.jpg?width=550',
    name: 'Schezwan Meatball & Capsicum',
    price: 10,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Pizza topped with our signature tandoori sauce, crunchy onion, flavorful chicken tikka and cheesy dressing.',
    id: 29,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/tandoori-tikka-&-onion-pan-personal.e47a58535b3ef920e00d559d79defad4.1.jpg?width=550',
    name: 'Tandoori Tikka & Onion',
    price: 5,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
  {
    description:
      'Pizza topped with our Classic Pan sauce, herbed chicken, flavorful sausages, juicy tomato and cheesy dressing.',
    id: 30,
    img: 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/classic-loaded-chicken-delight-pan-personal.8d0b6cb6bc34a734679ac40004edba10.1.jpg?width=550',
    name: 'Classic Loaded Chicken Delight',
    price: 9,
    quantity: 1,
    sizeandcrust: [[]],
    veg: false,
  },
];
